version: '3'
services:

  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160"
      - "4161"
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4150"
      - "4151"
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - "40004:4171"

  web:
    build: website
    command: bash -c "node server.js"
    depends_on:
      - nsqd
    ports:
      - "8084:8080"

  consumer:
    build: consumer
    command: /app/npl-consumer
    depends_on:
      - nsqlookupd
    ports:
      - "53000:2112"

  prom:
    image: prom/prometheus
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web-enable-lifecycle --config.file=/etc/prometheus/prometheus.yml

volumes:
  prometheus-data:
